eureka:
  client:
    service-url:
      defaultZone: http://${HOST_IP_ADDRESS:localhost}:9999/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_IP_ADDRESS:localhost}
#oauth 2 security
spring:
  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9000/realms/documentstorage}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:9000/realms/documentstorage/protocol/openid-connect/certs}