server:
  port: 9080
spring:
  #data source
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/metadataservice?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect