server:
  port: 9081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  #data source
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/storageservice?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    azure:
      storage:
        blob:
          container-name: luu-tru-tai-lieu
      key-vault:
        secret:
          property-source-enabled: true
          property-sources:
            - endpoint: https://luutrutailieukeyvault.vault.azure.net/
              retry:
                mode: exponential
                exponential:
                  max-retries: 4
                  base-delay: PT0.0801S
                  max-delay: PT9S
azure:
  blob-storage:
    connection-string: ${azurestorageconnectionstring}
    account-name: ${AZURE_STORAGE_CONTAINER_NAME:tathanhmycv}